enum ErrorCode {
  AUTH_EXCEED_RETRY_PASSWORD_MAXIMUM = 'AUTH_EXCEED_RETRY_PASSWORD_MAXIMUM',
  AUTH_INVALID_PASSWORD = 'AUTH_INVALID_PASSWORD',
  CAMERA_ID_NOT_EXIST = 'CAMERA_ID_NOT_EXIST',
  FORBIDDEN = 'FORBIDDEN',
  GROUP_LEVEL_LIMIT_REACH = 'GROUP_LEVEL_LIMIT_REACH',
  INPUT_PARAMETERS_INVALID = 'INPUT_PARAMETERS_INVALID',
  ROLE_TEMPLATE_DUPLICATED = 'ROLE_TEMPLATE_DUPLICATED',
  ROLE_TEMPLATES_LIMIT_REACH = 'ROLE_TEMPLATES_LIMIT_REACH',
  RULE_NAME_DUPLICATED = 'RULE_NAME_DUPLICATED',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  USER_ALREADY_EXISTED = 'USER_ALREADY_EXISTED',
  DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND',
  NAME_DUPLICATED = 'NAME_DUPLICATED',
}

export default ErrorCode;
